### ISSUE TITLE
Activity Stream Not Loading on Space or Dashboard Sidebar

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#19]
As of 13 June at 3:30, the activity stream is not loading on dev. 

<img width="1174" alt="activities_not_loading" src="https://cloud.githubusercontent.com/assets/273429/16020421/a489a66c-3173-11e6-868f-613715bd1b24.png">

<img width="1197" alt="activities_not_loading_sidebar" src="https://cloud.githubusercontent.com/assets/273429/16020453/c8d13a58-3173-11e6-9a16-6877751366a5.png">

**Comment by Guihrmsfo** [comment]
Hey Nathan, this issue happens when you create a new content and it fails for some reason. Humhub still creates the activity and when it tries to load the wall entry in activities stream, it won't find the new object (because it doesn't exist).
I fixed for now, but we need to find out what caused the bug.

**Comment by Guihrmsfo** [comment]
This issue isn't traceable now, so I'll close it.
Renata told me that a permission denied (searchdb) error happened a few hours ago, so probably that's the reason. If ever happen again, please tell me what's your latest action before the anomaly.
