### ISSUE TITLE
Zend Lucene Search index getting offset

### ISSUE THREAD

**Issue by JayantGandhi** [EvokeNet/humhub#210]
the search indexes somehow got offset and caused multiple errors throughout the site - temporary fix was to rebuild the indexes, but no guarantee that it won't happen again...

**Comment by nathanverrill** [comment]
Is there a way we can run something periodically to help with this? Or redirect the user to the home page when the error occurs, since much of the site still functions?

PHP Notice – yii\base\ErrorException

Uninitialized string offset: 0
1. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php at line 79
70717273747576777879808182838485868788     \* Reads an integer from the current position in the file
     \* and advances the file pointer.
     *
     \* @return integer
     */
    public function readInt()
    {
        $str = $this->_fread(4);

```
    return  ord($str[0]) << 24 |
            ord($str[1]) << 16 |
            ord($str[2]) << 8  |
            ord($str[3]);
}


/**
 * Writes an integer to the end of file.
 *
```
1. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php at line 79 – yii\base\ErrorHandler::handleError(8, 'Uninitialized string offset: 0', '/home/ubuntu/humhub/protected/ve...', 79, ...)
   73747576777879808182838485     \* @return integer
    */
   public function readInt()
   {
       $str = $this->_fread(4);
   
   ```
   return  ord($str[0]) << 24 |
           ord($str[1]) << 16 |
           ord($str[2]) << 8  |
           ord($str[3]);
   ```
   
   }
2. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php at line 269 – ZendSearch\Lucene\Storage\File\AbstractFile::readInt()
   263264265266267268269270271272273274275     \* @throws \ZendSearch\Lucene\Exception\RuntimeException
    */
   private function _readSegmentsFile()
   {
       $segmentsFile = $this->_directory->getFileObject(self::getSegmentFileName($this->_generation));
   
   ```
   $format = $segmentsFile->readInt();
   
   if ($format == (int)0xFFFFFFFC) {
       $this->_formatVersion = self::FORMAT_2_3;
   } elseif ($format == (int)0xFFFFFFFD) {
       $this->_formatVersion = self::FORMAT_2_1;
   } else {
   ```
3. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php at line 420 – ZendSearch\Lucene\Index::_readSegmentsFile()
   414415416417418419420421422423424425426 
       if ($this->_generation == -1) {
           throw new RuntimeException('Index doesn\'t exists in the specified directory.');
       } elseif ($this->_generation == 0) {
           $this->_readPre21SegmentsFile();
       } else {
           $this->_readSegmentsFile();
       }
   }
   
   /**
   - Object destructor
     */
4. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Lucene.php at line 67 – ZendSearch\Lucene\Index::__construct('/home/ubuntu/humhub/protected/ru...', false)
   61626364656667686970717273     *
   - @param mixed $directory
   - @return \ZendSearch\Lucene\SearchIndexInterface
     */
     public static function open($directory)
     {
     return new Index($directory, false);
     }
   
   /**
   - @throws \ZendSearch\Lucene\Exception\UnsupportedMethodCallException
     */
     public function __construct()
5. in /home/ubuntu/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php at line 266 – ZendSearch\Lucene\Lucene::open('/home/ubuntu/humhub/protected/ru...')
   260261262263264265266267268269270271272 
       \ZendSearch\Lucene\Search\QueryParser::setDefaultEncoding('utf-8');
       \ZendSearch\Lucene\Analysis\Analyzer\Analyzer::setDefault(new \ZendSearch\Lucene\Analysis\Analyzer\Common\Utf8Num\CaseInsensitive());
       \ZendSearch\Lucene\Search\QueryParser::setDefaultOperator(\ZendSearch\Lucene\Search\QueryParser::B_AND);
   
   ```
   try {
       $index = \ZendSearch\Lucene\Lucene::open($this->getIndexPath());
   } catch (\ZendSearch\Lucene\Exception\RuntimeException $ex) {
       $index = \ZendSearch\Lucene\Lucene::create($this->getIndexPath());
   }
   
   $this->index = $index;
   return $index;
   ```
6. in /home/ubuntu/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php at line 105 – humhub\modules\search\engine\ZendLuceneSearch::getIndex()
   99100101102103104105106107108109110111    }
   
   public function find($keyword, Array $options)
   {
       $options = $this->setDefaultFindOptions($options);
   
   ```
   $index = $this->getIndex();
   $keyword = str_replace(array('*', '?', '_', '$'), ' ', mb_strtolower($keyword, 'utf-8'));
   
   if (!isset($options['sortField']) || $options['sortField'] == "") {
       $hits = new \ArrayObject($index->find($this->buildQuery($keyword, $options)));
   } else {
       $hits = new \ArrayObject($index->find($this->buildQuery($keyword, $options), $options['sortField']));
   ```
7. in /home/ubuntu/humhub/protected/humhub/modules/directory/controllers/DirectoryController.php at line 96 – humhub\modules\search\engine\ZendLuceneSearch::find('', ['model' => 'humhub\modules\user\models\User', 'page' => 1, 'pageSize' => 25])
   90919293949596979899100101102        }
   
   ```
   if ($group !== null) {
       $searchOptions['filters'] = ['groupId' => $group->id];
   }
   
   $searchResultSet = Yii::$app->search->find($keyword, $searchOptions);
   
   $pagination = new \yii\data\Pagination(['totalCount' => $searchResultSet->total, 'pageSize' => $searchResultSet->pageSize]);
   
   \yii\base\Event::on(Sidebar::className(), Sidebar::EVENT_INIT, function($event) {
       $event->sender->addWidget(\humhub\modules\directory\widgets\NewMembers::className(), [], ['sortOrder' => 10]);
       $event->sender->addWidget(\humhub\modules\directory\widgets\MemberStatistics::className(), [], ['sortOrder' => 20]);
   ```
8. humhub\modules\directory\controllers\DirectoryController::actionMembers()
9. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\directory\controllers\DirectoryController, 'actionMembers'], [])
10. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'directory/directory/members'])
11. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('members', ['r' => 'directory/directory/members'])
12. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('directory/directory/members', ['r' => 'directory/directory/members'])
13. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
14. in /home/ubuntu/humhub/index.php at line 25 – yii\base\Application::run()
    19202122232425    require(**DIR** . '/protected/humhub/config/web.php'),
    (is_readable(**DIR** . '/protected/config/dynamic.php')) ? require(**DIR** . '/protected/config/dynamic.php') : [],
    require(**DIR** . '/protected/config/common.php'),
    require(**DIR** . '/protected/config/web.php')
    );

(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'directory/directory/members',
];

$_COOKIE = [
    '_csrf' => '173d2175d53702a6758a4fecac66b0b0b53c857d3dd7df0740d8be0769953f7ca:2:{i:0;s:5:"_csrf";i:1;s:32:"W0Tgr7bbrJTCOKJXa-iDiVxcPfcY5qMu";}',
    'pm_space-members-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_profile-follower-panel' => 'expanded',
    'language' => '2e2c7fa0242766f45a734a15a20a634d37b58d606f6f05f0aad08c2640adbbeea:2:{i:0;s:8:"language";i:1;s:2:"es";}',
    '_gat' => '1',
    'PHPSESSID' => '1bksfd2kb6p9qot2ech8566ou0',
    '_ga' => 'GA1.2.1926725822.1471014321',
    '_identity' => '59ae5cccac10c04bf5e1113b038afbe1d9553e85c93d4bef0e9d3699a3270fe1a:2:{i:0;s:9:"_identity";i:1;s:51:"[48,"73ec8dfe-93f3-406d-a15f-b86151b8bbff",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/',
    '__id' => 48,
];
Yii Framework
2016-10-12, 08:30:42

Apache/2.4.7 (Ubuntu)
Yii Framework/2.0.7

**Comment by rjapur** [comment]
Lucas answered new version of humhub has an improved system of indexes. For the current version, he could not find the source of the issue.

**Comment by nathanverrill** [comment]
Thanks Renata, new version is certainly something for us to discuss about post-soacha.

**Comment by rjapur** [comment]
As the only possible solution is to update (and we can't do it now), can be closed

**Comment by thomaswillecomme** [comment]
Hi ! I may have the same or similar issue. My index fails when browsing users or spaces 
it actually complains about a missing _11.cfs file which does not exists:
 ls humhub/protected/runtime/searchdb/
drwx---r-x    2 49373      users              22 Dec 29 18:42 .               
drwxr-xr-x    9 49373      users               9 Dec 29 17:39 ..
-rw-rw-rw-    1 49373      users             568 Dec 29 18:42 _10.cfs
-rw-rw-rw-    1 49373      users           11067 Dec 29 18:20 _v.cfs
-rw-rw-rw-    1 49373      users             295 Dec 29 18:21 _v.sti
-rw-rw-rw-    1 49373      users               9 Dec 29 18:21 _v_1.del
-rw-rw-rw-    1 49373      users            2809 Dec 29 18:20 _w.cfs
-rw-rw-rw-    1 49373      users             107 Dec 29 18:21 _w.sti
-rw-rw-rw-    1 49373      users            1013 Dec 29 18:31 _x.cfs
-rw-rw-rw-    1 49373      users             107 Dec 29 18:32 _x.sti
-rw-rw-rw-    1 49373      users               9 Dec 29 18:39 _x_1.del
-rw-rw-rw-    1 49373      users             983 Dec 29 18:39 _y.cfs
-rw-rw-rw-    1 49373      users             107 Dec 29 18:41 _y.sti
-rw-rw-rw-    1 49373      users             570 Dec 29 18:41 _z.cfs
-rw-rw-rw-    1 49373      users             107 Dec 29 18:42 _z.sti
-rw-rw-rw-    1 49373      users               9 Dec 29 18:42 _z_1.del
-rw-rw-rw-    1 49373      users               0 Dec 29 18:42 optimization.lock.file
-rw-rw-rw-    1 49373      users               0 Dec 29 18:42 read-lock-processing.lock.file
-rw-rw-rw-    1 49373      users               0 Jan  3 21:21 read.lock.file
-rw-rw-rw-    1 49373      users              20 Dec 29 18:42 segments.gen
-rw-rw-rw-    1 49373      users             169 Dec 29 18:42 segments_1x
-rw-rw-rw-    1 49373      users               0 Dec 29 18:42 write.lock.file

I don't think it's an access related issue as _10.cfs file have been created and is not empty.

**Comment by thomaswillecomme** [comment]
Well i fixed the index calling 

> humhub/protected/yii search/rebuild

as the issue 624 was stating #https://github.com/humhub/humhub/issues/624
Still, the index should not have been broken in the first place. I saw that it was breaking the cron jobs too

**Comment by Guihrmsfo** [comment]
Thank you, @thomaswillecomme 
Rebuilding it worked and since that time it didn't happen again, so I'm closing this issue.
