### ISSUE TITLE
Option to Add Novel Chapter before each mission

### ISSUE THREAD

**Issue by JayantGandhi** [EvokeNet/humhub#353]
Extend the Novel module so that it can
1) be organized by chapters (so pages are now sub grouped into chapters)
2) a chapter can be set to show when a user first enters a mission

There is already a pages model in the novel module.

**Comment by nathanverrill** [comment]
1. Page layout for illustration and text is one image that can be used, like the graphic novel pages
2. Tab strip on to top easily toggles between Chapter and Mission content
3. Chapter 2 heading is in HTML (font doesn't have to be this one, can match Evoke style)
4. Next/Previous links are on both chapter and novel pages; grayed out where appropriate if there isn't a next or previous. Links instead of buttons so they aren't too overwhelming in the UI.
5. HumHub sidebar modules are removed
6. Graphic Novel in top navigation changes to Novel, and goes to Mission 1 Chapter 1

![chapter-layout](https://cloud.githubusercontent.com/assets/273429/21815099/19a476fe-d721-11e6-9a94-379905de491d.png)

![literacy_chapter_2_placeholder](https://cloud.githubusercontent.com/assets/273429/21815236/8bdf04aa-d721-11e6-923e-a42876d39830.png)
